"""Stable boundary between the three-dimensional game engine and the Agent."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Protocol, TypeAlias


Face: TypeAlias = tuple[tuple[int, ...], ...]
Faces: TypeAlias = tuple[Face, Face, Face, Face, Face, Face]
Observation: TypeAlias = tuple[int, ...]


class Action(str, Enum):
    """Enumerate the six legal moves in the three-dimensional 2048 game."""

    LEFT = "left"
    RIGHT = "right"
    UP = "up"
    DOWN = "down"
    W = "w"
    S = "s"


@dataclass(frozen=True)
class GameSnapshot:
    """Represent the observable state returned by a six-face game engine."""

    faces: Faces
    score: int
    won: bool
    game_over: bool


@dataclass(frozen=True)
class EngineMove:
    """Represent one engine transition and the score generated by its merges."""

    snapshot: GameSnapshot
    moved: bool
    score_delta: int


class SixDirectionGameEngine(Protocol):
    """Define the only game-engine operations required by the learning Agent."""

    def reset(self, seed: int | None = None) -> GameSnapshot:
        """Start a game and return its first observable state."""

    def move(self, action: Action) -> EngineMove:
        """Apply one legal action and return its transition result."""
