"""Stable boundary between the three-dimensional game engine and the Agent."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Protocol, TypeAlias


Cube: TypeAlias = tuple[tuple[tuple[int, ...], ...], ...]
Observation: TypeAlias = tuple[int, ...]


class Action(str, Enum):
    """Enumerate the six legal moves implemented by Board3D."""

    LEFT = "left"
    RIGHT = "right"
    UP = "up"
    DOWN = "down"
    FORWARD = "forward"
    BACK = "back"


@dataclass(frozen=True)
class GameSnapshot:
    """Represent the observable state returned by the 4x4x4 game engine."""

    grid: Cube
    score: int
    won: bool
    game_over: bool


@dataclass(frozen=True)
class EngineMove:
    """Represent one engine transition and the score generated by its merges."""

    snapshot: GameSnapshot
    moved: bool
    score_delta: int


class SixDirectionGameEngine(Protocol):
    """Define the only game-engine operations required by the learning Agent."""

    def reset(self, seed: int | None = None) -> GameSnapshot:
        """Start a game and return its first observable state."""

    def move(self, action: Action) -> EngineMove:
        """Apply one legal action and return its transition result."""
